name: spicy_bowl
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  url_launcher: ^6.0.20
  intl_phone_field: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
   # - assets/background.jpg
   # - assets/home.jpg
    - assets/home.png
   # - assets/background2.jpg
    - assets/bgg.jpg
    - assets/signin.jpeg
    - assets/google.png
    - assets/whitebg.png
    - assets/signup.jpg

